### ISSUE TITLE
建议改名

### ISSUE THREAD

**Issue by kuzen** [wangdoc/clang-tutorial#1]
教程挺好的，但是clang有歧义，为了更符合教程内容，建议改个名字

**Comment by jserv** [comment]
我同意 @kuzen 的意見，改為 "cprog" 或 "c-prog" 一類的名稱可消除歧義。

**Comment by ruanyf** [comment]
我也犹豫很久。

单个字母`c`似乎不适合作为项目 ID。其它名字里面，只想到了`clang`，可惜与编译工具重名。

我再思考一下吧。

**Comment by alexkuang0** [comment]
感觉可以用 `c-tutorial` 或者 `c-lang-tutorial` 。
