### ISSUE TITLE
C语言教程 #文件指针 中的#6.freopen() 函数的示例少了一个星号*

### ISSUE THREAD

**Issue by wanlala** [wangdoc/clang-tutorial#101]
https://wangdoc.com/clang/file#%E6%96%87%E4%BB%B6%E6%8C%87%E9%92%88
![image](https://github.com/wangdoc/clang-tutorial/assets/43746907/15eb6fbe-525d-419c-bb14-166313e74c52)

freopen()的原型中少了一个星号 FILE* stream
FILE* freopen(char* filename, char* mode, FILE stream); --> FILE* freopen(char* filename, char* mode, FILE* stream);

另：谢谢写的教程！

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
