### ISSUE TITLE
右侧导航建议

### ISSUE THREAD

**Issue by youyu** [wangdoc/clang-tutorial#14]
WangDoc网站的文字一般挺长的，有两个建议
1、导航栏能不能随着滚动条走，总是显示在屏幕右侧，便于选择阅读，特别是再次阅读时是选读的。
2、建议加一个返回顶部的按钮小火箭，便于回到页面内导航，复习阅读。
不知是否可行
感谢阮老师的辛苦付出和无私奉献%%%STO

**Comment by ruanyf** [comment]
导航栏放在右侧，就不能做固定了，因为会出现垂直滚动条，跟页面滚动条并列在一起，十分难看。后来，看看改到左侧怎么样。

返回顶部按钮，已经有了，鼠标放在每个章节标题上就能看到。
