### ISSUE TITLE
几条建议

### ISSUE THREAD

**Issue by imba-tjd** [wangdoc/clang-tutorial#19]
flow-control 9 goto 语句

> goto 的一个主要用法是跳出多层循环。
> 上面代码有很复杂的嵌套循环，不使用 goto 的话，想要完全跳出所有循环，写起来很麻烦。

一般来说可以提取成一个函数，return时就全跳出了。

---

function 7.1 extern 说明符

> 对于多文件的项目，源码文件会用到其他文件声明的函数。这时，当前文件里面，需要给出外部函数的原型，并用extern说明该函数的定义来自其他文件。

函数的声明不需要extern，后面specifier这一章里也说了。

---

string

对于字符串常量，只在最开始写`char* s = 'xxx';`，等到引入无法修改的问题后，之后的代码一直用`const char *`。

---

struct

一般不说“struct命令”吧。

**Comment by jiaoqiyuan** [comment]
如果只是想跳出循环，后面还有处理逻辑，return就不适合了。:)

**Comment by imba-tjd** [comment]
只有后面的逻辑与循环中间有耦合，才会不适合。我自己只在写Trie树时遇到过，或者是JSON解析器的时候？忘了。大部分时候都是可以提取成函数的。

**Comment by jiaoqiyuan** [comment]
> 只有后面的逻辑与循环中间有耦合，才会不适合。我自己只在写Trie树时遇到过，或者是JSON解析器的时候？忘了。大部分时候都是可以提取成函数的。

是的。

**Comment by ruanyf** [comment]
谢谢指出，意见非常好，已经改进。

**Comment by imba-tjd** [comment]
少打了个字:joy:

![image](https://user-images.githubusercontent.com/24759802/132648168-62b3a305-9acd-409f-89a6-dff190922541.png)
