### ISSUE TITLE
数据类型 -> 函数 中的笔误

### ISSUE THREAD

**Issue by wenLiangcan** [wangdoc/clang-tutorial#20]
![Screenshot_20210909-005626](https://user-images.githubusercontent.com/1244181/132552446-fed4be38-7636-46d5-b6bb-1bc934bb784e.jpg)
 变量 `a`,  `b` 应为 `m`， `n` ？

**Comment by jiaoqiyuan** [comment]
我觉得应该是 `m, n` -> `a, b` 。:）

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
