### ISSUE TITLE
让我感到麻烦的并不是C语言的语法，毕竟资料多，多看书多敲代码就可以。但是C/C++ 项目构建，引用第三方库实在复杂。

### ISSUE THREAD

**Issue by MoonandMind** [wangdoc/clang-tutorial#24]
可以多介绍一些如何引用第三方库相关的知识吗？比如将ffmpeg，boost 编译成动态链接库，也不知道该看什么资料，所查到的都是雷同的编译脚本。

**Comment by ruanyf** [comment]
这些都要后面考虑了，如果有中级教程或者 Linux 系统编程。目前，项目重点还是补全，不是深化。
