### ISSUE TITLE
multifile.md 中的一个疑问

### ISSUE THREAD

**Issue by logicshan** [wangdoc/clang-tutorial#27]
https://github.com/wangdoc/clang-tutorial/blame/main/docs/multifile.md#L80

根据上下文来看, 这里的代码是否应为

```c
// File bar.c

#include "bar.h"

int add(int x, int y) {
  return x + y;
}
```

**Comment by logicshan** [comment]
阮老师, "bar.h" 里不是包含 `int add(int, int);` 这一行吗? 为什么写成

```c
// File bar.c
#include "bar.h"

int add(int, int);
```
根据你上面一句, "这样可以让编译器验证，函数原型与函数定义是否一致。" 不是应该写 `add` 的定义吗?

这里我可能理解的不太充分

**Comment by ruanyf** [comment]
不好意思，我改的时候没仔细看，疏忽了。

谢谢提醒，已经补上函数定义了。
