### ISSUE TITLE
array.md 中的疑问

### ISSUE THREAD

**Issue by logicshan** [wangdoc/clang-tutorial#28]
https://github.com/wangdoc/clang-tutorial/blame/main/docs/array.md#L205

```c
int n = a + b;
int a[n];
```

两行都有 `a`. 没有 get 到这个例子的点

**Comment by liuyunli** [comment]
应该是
```
int n = a+b;
int m[n];
```
代表数组的长度为计算值而非常量

**Comment by logicshan** [comment]
那这里算个笔误吧. 不过这里把第二行的 `a` 改为 `m`, 下文也要做相应修改

**Comment by ruanyf** [comment]
这里是笔误，已经改过来了。
