### ISSUE TITLE
ch11（内存管理）中代码注释的问题

### ISSUE THREAD

**Issue by ocmcc** [wangdoc/clang-tutorial#30]
2.void指针 中的第一段代码

int x = 10;

void* p = &x;  // 整数指针转为 void 指针
int* q = p;  // void 指针转为整数指针

这里的两行注释是不是顺序颠倒了，第一行不应该是无类型指针p转为int类型指针吗？还是我理解有问题？

**Comment by liuyunli** [comment]
"&x" 为整数指针。“void* p = &x” 定义了一个void 类型的指针p, 并赋值为整数指针的值。故称（整数指针转为 void 指针）
下一行同理

**Comment by ruanyf** [comment]
@ocmcc 写得不够清楚，我已经改过来了，一会提交。
