### ISSUE TITLE
标准库章节-errno.h

### ISSUE THREAD

**Issue by WizardPro** [wangdoc/clang-tutorial#31]
取值范围错误（ERANGE）：函数的返回值太大，无法用返回类型白哦是。

这里最后的'白哦是'是不是写错了？
还是故意卖萌呢？😆

**Comment by ruanyf** [comment]
谢谢指出，已经改过来了。

https://github.com/wangdoc/clang-tutorial/commit/8e626d7aa15497fb6ac74f68668e71d63fccc9ee
