### ISSUE TITLE
file.md笔误

### ISSUE THREAD

**Issue by batouy** [wangdoc/clang-tutorial#37]
一、第10项 fscanf()：......而fscanf()是从文件读入数据，它的**原因**定义在头文件stdio.h......

此处应该是“它的**原型**定义在头文件stdio.h”

二、第13项fwrite(): fwrite()以及后面要介绍的 **fwrite()**，比较适合读写二进制数据......

此处应该是指后面的 **fread** 函数吧

**Comment by ruanyf** [comment]
谢谢指出，已经更正了，稍后推送代码。
