### ISSUE TITLE
建议添加文档参考资料的链接

### ISSUE THREAD

**Issue by ligaowang** [wangdoc/clang-tutorial#39]
读了阮老师的ssh系列和C系列，感觉收获很大，但总有种拾人牙慧的感觉，如果能把笔记对应的参考书籍或者文档链接也发一下，就再好不过了，我想对照着看看，这样不仅能巩固一下，也能学学如何做笔记的。

**Comment by ruanyf** [comment]
ES6 教程有《参考文档》页面，但是效果一般。

C 语言教程主要参考了很多教科书，所以就没列出参考文档。以后会尽量加上资料来源。
