### ISSUE TITLE
字符串章节，书写错误

### ISSUE THREAD

**Issue by Chrunge** [wangdoc/clang-tutorial#40]
”C 语言允许合并多个字符串字面量“
应该为： “C 语言允许合并多个字符串字**变**量”

内存管理章节：
“指针变量必须有类型，否则编译器无法知道，如何解读内存块保存的二进制数据。“
建议改成” 指针变量必须有类型，否则编译器不知道如何解读内存块保存的二进制数据。“

**Comment by ruanyf** [comment]
你的第一点，原文是对的，C 语言只允许字符串字面量的合并，比如`printf("A""B""C\n")`。

你的第二点属于文字风格，不是语病。
