### ISSUE TITLE
9. 数组 - 4. 变长数组

### ISSUE THREAD

**Issue by jamesfancy** [wangdoc/clang-tutorial#41]
> 数组声明的时候，数组长度除了使用常量，也可以使用变量。

有点英式写法，建议：声明数组的时候，数组长度既可以是常量，也可以是变量。

> 任何长度需要运行时才能确定的数组，都是变长数组。

建议：任何需要运行时才能确定长度的数组 ...

> 上面示例中，三个数组的长度都需要运行代码才能直到，所以它们都是变长数组。

拼写：直到⇒知道，并且建议改成：才能确定

**Comment by ruanyf** [comment]
错别字已经改正了。

语言的部分，说实话我体会不到区别，还是按照自己的口语习惯表达了。

**Comment by jamesfancy** [comment]
> 语言的部分，说实话我体会不到区别，还是按照自己的口语习惯表达了。

哈哈，就按你的来，这才是你的风格。如果改了，整体看起来可能反而会别扭。
