### ISSUE TITLE
for循环变量的作用域问题

### ISSUE THREAD

**Issue by niaucz** [wangdoc/clang-tutorial#42]
[变量的作用域](https://wangdoc.com/clang/variable.html#%E5%8F%98%E9%87%8F%E7%9A%84%E4%BD%9C%E7%94%A8%E5%9F%9F)
链接文章结尾处的代码

```c
for (int i = 0; i < 5; i++) {
  int i = 999;
  printf("%d\n", i);
}

printf("%d\n", i); // 非法
```

运行报错 `error: redeclaration of 'int i'`

![image](https://user-images.githubusercontent.com/29652276/134799419-e0a0512c-cf89-47fa-b479-35a6e0f789fa.png)

老师想表达的是嵌套循环的作用域？
```c
for (int i = 0; i < 5; i++)
{
    for (int i = 0; i < 3; i++)
    {
        //...
    }
}
```
这样是可以重复定义`i`变量的。
![image](https://user-images.githubusercontent.com/29652276/134799365-417fd498-56dc-4278-89ff-b5cdc4cab023.png)

**Comment by ruanyf** [comment]
你用的不是 GCC 吧。
