### ISSUE TITLE
运算符-> 逗号运算符 运算结果有点问题

### ISSUE THREAD

**Issue by jiaoqiyuan** [wangdoc/clang-tutorial#6]
> ```x = 1, 2, 3;```
> 上面示例中，逗号的优先级高于赋值运算符，所以会执行。由于逗号运算符返回最后一个表达式的值，所以变量x等于3。

`x = 1, 2, 3;` 执行后 x 的结果是 1，`逗号的优先级高于赋值运算符` 这句话有误，应该是 `逗号的优先级低于赋值运算符，且按从左到右的顺序运算`。所以先运行 `=` 运算符，直接将 1 赋值给 x。

`x = 1, 2, 3;` 可以看作 `(x = 1), 2, 3;` 整个表达式的返回值是 3。

**Comment by jiaoqiyuan** [comment]
这里我觉得阮老师想要表达的应该是 `x = (1, 2, 3);` 这样可以排除 = 运算符的干扰，突出逗号运算符的作用。

**Comment by ruanyf** [comment]
谢谢指出。我这里写错了，已经改过来了。
