### ISSUE TITLE
《C 语言教程》中第9章【数组】的第7个知识点【数组的复制】关于memcpy用法举例会造成内存溢出

### ISSUE THREAD

**Issue by guggle241** [wangdoc/clang-tutorial#77]
![图片](https://user-images.githubusercontent.com/10356615/162561304-07dc5bd8-9a4d-47c5-ae86-aaa67b417b5c.png)
正确写法: memcpy(a, b, sizeof(a));
如果b数组比a数组的长度长,若使用教程中的代码,会导致a数组之后的内存空间被赋值,造成内存泄露,还望修正~

**Comment by ruanyf** [comment]
a 就是一个起始地址而已啊。
