### ISSUE TITLE
docs-lib-locale中的一个小错误

### ISSUE THREAD

**Issue by WangShuoran** [wangdoc/clang-tutorial#85]
https://www.bookstack.cn/read/wangdoc-clang-tutorial/docs-lib-locale.h.md

<img width="382" alt="image" src="https://user-images.githubusercontent.com/43474491/206895830-6f5c5968-633e-432b-aa9c-87f2165f0225.png">

少了一个e!

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
