### ISSUE TITLE
逗号表达式增加一个示例

### ISSUE THREAD

**Issue by luzhixing12345** [wangdoc/clang-tutorial#90]
[原文](https://wangdoc.com/clang/operator#%E9%80%97%E5%8F%B7%E8%BF%90%E7%AE%97%E7%AC%A6)这里的示例并不能充分的反映出上面提到的 `逗号运算符返回最后一个表达式的值，作为整个语句的值`

```c
int x;
x = 1, 2, 3;
```

我建议可以修改成

```c
int x,y;
x = 1, 2, 3;
y = (1, 2, 3);
printf("%d\n",x); // 1
printf("%d\n",y); // 3
```

**Comment by ruanyf** [comment]
谢谢指出，原来的例子确实不佳，已经改正了。
