### ISSUE TITLE
一点表诉错误

### ISSUE THREAD

**Issue by wangwenjun08** [wangdoc/clang-tutorial#95]
老师，在【运算符】那一章，关于【%】的表述有一点错误: “运算符%表示求模运算”。取模和取余计算方并不完全相同，在取整数商的时候，取模是floor()函数策略,取余是fix()函数策略。在C中是取余运算

**Comment by ruanyf** [comment]
“取模”就是计算余数吧。

我查了[维基百科](https://zh.wikipedia.org/wiki/%E6%A8%A1%E9%99%A4)：

> 模除（又称模数、取模操作、取模运算等，英语：modulo 有时也称作 modulus）得到的是一个数除以另一个数的余数。
