### ISSUE TITLE
Variable章节中对于for循环省略了{}的原因说明

### ISSUE THREAD

**Issue by Cyxxxxxxxx** [wangdoc/clang-tutorial#97]
![Snipaste_2023-10-31_01-48-46](https://github.com/wangdoc/clang-tutorial/assets/92504163/bd3bd4cf-162d-4655-9909-4d6676106d50)
建议--此处，for省略了大括号可行，是否加上详细解释：在循环体内只有一行语句的时候，可以省略{}
这样更为严谨。

**Comment by ruanyf** [comment]
见《流程控制》一章。
